server:
  port: 2004

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(YXXxUQzO2qaxX2bJzDNKZg==)
    password: ENC(iIR6UImHnGfe4GOkWBFxtw==)
    url: ENC(ymGGfyoWPXrkEGMvkU2sPbUvJbJjpBP+W1ttEh6luvt83MdK3iuyOvroM6kOIFAy2E9Fl81OTcvKNRJTXrNEKyX5Gz3uclh1p/DIfpcMqqJjDNFxbrXPo3l58nKodiTtaailQFt344KgkkG4CIl5WTfDIDMNSOjvDFINv1FUJ04=)
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  config: classpath:logback.xml
